name: Update Diary Index

on:
  push:
    paths:
      - 'diary/entries/*.md'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Debug repository structure
      run: ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Update diary index.json
      run: |
        node <<EOF
        const fs = require('fs');
        const path = require('path');

        const entriesDir = path.join(__dirname, 'diary/entries');
        const indexFile = path.join(__dirname, 'diary/index.json');

        const files = fs.readdirSync(entriesDir).filter(file => file.endsWith('.md'));

        const entries = files.map(file => {
          const content = fs.readFileSync(path.join(entriesDir, file), 'utf-8');
          const frontmatterMatch = content.match(/^---\n([\s\S]+?)\n---/);
          if (!frontmatterMatch) return null;

          const frontmatter = Object.fromEntries(
            frontmatterMatch[1]
              .split('\n')
              .map(line => line.split(':').map(part => part.trim()))
          );

          return {
            title: frontmatter.title || '',
            date: frontmatter.date || '',
            slug: file.replace('.md', ''),
            id: frontmatter.id || '',
            week: frontmatter.week || '',
            summary: frontmatter.summary || '',
            tags: frontmatter.tags ? JSON.parse(frontmatter.tags.replace(/'/g, '"')) : []
          };
        }).filter(entry => entry);

        fs.writeFileSync(indexFile, JSON.stringify(entries, null, 2));
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add diary/index.json
        git commit -m "Update diary index.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}